const abc = { 
    'a': 1, 
    'b': 2, 
    'c': 3, 
    'd': 4,
    'e': 5,
    'f': 6,
    'g': 7,
    'h': 8,
    'i': 9,
    'j': 10,
    'k': 11,
    'l': 12,
    'm': 13,
    'n': 14,
    'o': 15,
    'p': 16,
    'q': 17,
    'r': 18, 
    's': 19,
    't': 20,
    'u': 21,
    'v': 22,
    'w': 23,
    'x': 24,
    'y': 25,
    'z': 26,
    'A': 27, 
    'B': 28, 
    'C': 29, 
    'D': 30,
    'E': 31,
    'F': 32,
    'G': 33,
    'H': 34,
    'I': 35,
    'J': 36,
    'K': 37,
    'L': 38,
    'M': 39,
    'N': 40,
    'O': 41,
    'P': 42,
    'Q': 43,
    'R': 44, 
    'S': 45,
    'T': 46,
    'U': 47,
    'V': 48,
    'W': 49,
    'X': 50,
    'Y': 51,
    'Z': 52
}

const inputRucksacks = `mjpsHcssDzLTzMsz
tFhbtClRVtbhRCGBFntNTrLhqrwqWMDMTWTqMq
LltbngLGRSBgSgGRCJdSdQHvdfmQccmjSQ
lBslsZDDWdGdGpSMts
grQhDvqLQHDNGJJtbRMQQJ
HChCTnnLCgCrTZPPFzzVPcVD
ShrzjhNGrNqrhWnHHfVHbhnHbbhH
RBsvcBcDCdsRTsvgCgcPFRQpVQGQJPVFbnJfbJ
DvsTsdlCBsGLrjzmlqqz
WJJqZTgCnBLGCZBJCJnTLggTDDSDDMNdDSdbdSSsWDFfMsFf
PVjqpVHmPpvmcjhrRprFmQQffbfNbQMMsSMQNQ
cwcpRvrVlVgwtBwZqBzZ
qfJJmpqpmhsggvvpVPZCrhdFLFzZFDdLLh
CtCTBctGcGLSzZddGZSW
RlNjBCnjttBHHMMcQHCsRfsbfwgggmmJvmgfpm
ZmcgBBZhZMsnqnCPjpHPjLHp
dGbNwNtlTMTzGfNvTvdwNGVLPpQHPjLQPCpCjPqjLbpLPR
dvDTdfvNBhDZMBDZ
cvvRvbqcllbBVlvVVbVVlbVDjRjDjdMsHPZPGdDPGPHrDP
FwtpfwJtWwNtTTNnwFCtjDJsQdQPPPPMrjrPJHjH
CwFpnppgntShgbsscbms
cWMFMQpFNcvNDdBDgdsT
MPrrfrCHBBsDZCBJ
LmLjMLjjLWpVcRVR
ZrRZqlZMqTWrMDqwvnvVtnsvddvVnlVf
pQNhhLNNGmLjhhcfvndDpffdfdVf
QGjCLCQGmNgPBQDFFgTMJWWwMRTrTZWWBWTr
WrZWZPHHWZHprZVmVvqddBttBBhGhtvh
gzDlMTJDMfqhBGllhl
jJLqMMDDbbqjLpPHcsHLWZspPr
bsSVRVGsrDstrrSjcQjcjlPwzjQl
gHBggFNTTvTgfqgCFzljWwLWQQQnrwQWnf
NvJHgpgHvqBhNBJhHTvpBCJCZmtdpDsGsZdZMZRbVbbMdrZs
MPPtPwPnRnMPPnwrtNSGgLSCGGGNSLtSgD
hBhWFjfCsTbbbWqFFWBBqBhsWZVGSVglZHLSVDlNWDNHHGgV
zsCfTsTCMdmRPwzQ
JVQVvvszzvTsVsVJjctppcCtjtPRcTlP
MdFgqSddMqMDbtDlNjRDSR
qFZWZqwHlZfZvzvZfLZn
vpqwQSsHSHDQzDpgzwZlRLRZRRZTnTrrvGhh
JBcdmbmFMPgPbgfrZRZnRFFnrnLRln
JNdBNgbdJmPMWSSDzwVDtwSWWW
BDMcDDppHCStpWcHBDNtzPJjqGlllPMJzPGjwjlq
CZdZLmgCdqbPzjblZj
vndLfnghRQmVrhdvgBHpSCDWHBBCVHNppD
WrhrJJGSWzpTWwts
VlLPmqgmRNZRGwsvttjgcwsT
PDZmlbdVqLmPlddVNRDmmmbbSFHrCFQCnFBFJHSJGrDQCBrr
hvPdpvhHvHvPrNfVhDfjggFfRV
zlGwJGslsSDRfjsg
MJMWjMJzwqWGzJwMqJBTCmHndPPdCBvmdCpmHn
PVWFpQhJhFJpGbRCvRHGCp
jgslDjftsqhNglTgllgTqMnlHwCcvwZwRccSRCbGSGbCMHRw
TgjhNNnjlTfjTdDqTfhjnmzmWPzWrLdrQBPJFWJWBB
qPPRMPlfSzSSSPPnnLnqMlpQQtrrtmWpbFtQrdzrtrWt
BBvCcwsVThsBgswDBCFQHQpdmQvtrFpWFvWp
gCghTJgVCgDGVMlRGMqZnSWqlM
RWbHvrbHBsbWBHJWvJwMtmdZwdtmdvwMZQff
DRVjcqhRchhGGllhCgdGQQzfttzGQGwQfg
cDRljchpqTcjDFTFVcPcPCWBHpNnJNNSnbWbHHrSpWHr
dtHrRrBHrCRhddftjgBrRhgjsbbbMpbSWSTjWcsDTWDbcW
GQPFVQVQnJlqVMDcMzpDfzpDVD
qZZJFLlLnvFFGPGLPqnJvwQldfgHrBRBmBhgNBRHghNhhwRg
rLbrZhPgqZhMdVFSFTSGCqFG
zsszfRzjtHtzvRTSDdFFCtdDdtND
fcwllfmwzRHlfmmzFvQQLrgLMLBZhJQZPrZhJLhW
sllrCfpQQJpMHLgzwDwpNqzzVDpV
RZPFZPGcSMFtGPRGMwNDVwdRgzvNwgqNvg
hBmbMcBmcThmcGtSFTZfQCJjrHLJfsjhWJssJl
DqGCbGfCRhfZCVbbqDJJGJBgRNpNdpBNNgNBBNwHnRgt
rcWSsSSPSQtwBwHD
MLscLMzvvTvcTLzvWWFDPTTrGqmFGGqCZJGbblbVbVZZVmFJ
FprpsLQTrstQHNmVSVml
JMggWPggWcRbwgJPCGMcGcfmzHlMNSjfzVNhHfVtzSMz
cwnPnBwgnGRgRCgRbWJLpFsLtFBLFrDLFZZDrL
lVgjLLLMgFMDCwCFqCRbngsvnGSvnSGndbsfgf
WZJcTWcNTmJZphmTJJNQHcdvfdbvnRRGbGthdrbttfSv
ZPQTJTpTNPJNQTmJRBZJNBHjwMVwPCMwVlVzjwwzqqjVjL
hznNhNQNQFDWVFmDQm
SMqZBMMbBvDbHPzzdVPH
zzzTBTMLNTgpnTTh
NLCdmsdCVLGHCHdQzzmznnFwRjFMDMwpTBjDRpnpTBMJ
PrcfcrglcfWbSqgrlqvShrwpJpDBFJHpBWjTDTRTRTTB
crSgSHtPttfdLGmtzzZNNV
BTlTVqCBqtTcBqVhWlsJjDvsnLsvlvpJPj
gMgggGZbSMzNRRRLmZZnQZQPPDvnsnDvJwwQ
dMRRmMgbNfRgmfSdGFgNgTBtrhrhqfWtLCCWLTWWHc
zcfVrPwnwrPmrvnjdFdBbHFFdd
CCqpSSQQpQZLDCSHPpBFvFBjTHRvRR
DMLGthLZMLtQGhGNMPqGSDflzfwcVmzJzsfgNVrswcrr
hSgvMTQvChSqPvhTrRLlVHJgfgRJlHHHJH
jmzsZzZzwmmLGGtwtVJWNNDRDtVcfVRl
GnBBLbzzzFszBFpzvSdrQQCTCQbhMvSQ
VHpTMrZMMbDbbpTZmQmTnmzhTqjqlWWQ
GGvgNsvNCNvvGvlqqdzWZmlsmZqZ
wNNNgccNGJSNBSRNBNvNcvJHLDDZMFRMppMLrfHDLbrrHF
spssbPMLpPllspGNsNWMrnwddnfcqrnwwwwMwM
VmQBFCjzzjmfnwbrngcVrd
FQbSFjBvvzsWvWGlvWNl
JLFSwfwRLLfGhnQJBQshvn
pZgNcpCWpWtcvhjGGjtVvszD
CccMcPcgTTCWmcZcWMcmTNZPmHdrqSHFRRrqwrSrRqwrHmsH
BPMhflJRhqnPNGjNRNRjgSRm
VdVsDswTVZbCwCZBrcDCczTwtjtNNjmjmgpmjpQggpGVSgQm
sTbWrsTBbrTPPnqlJnPPhW
nvrgjMWBvQWPvQnsZfGcZcRFdGFtdtZB
bHVDwmqNNDhHNzqpphLNHVLpSJcdZtfffRZdDgRFGSddcRZt
HNLNqNqLNbhqVVbClngjnQWPTWgsCgvT
tfstpcScscBTFTpFnsWSmgdzJlgmgBmPPzJmvdPm
jnrqrLHRwGrwhdPvvPvhjJmP
qqCLRCGrZZqCHRVtVWQptFWppnbcWb
wCDJZJgDwHpdqHhdGHBhhH
WSPmJMlmbSmztQlQsvPhnhGGdBddBqdGddTbVB
WzWQftWMSWtmvmmSWtMQPgggpZwLwZjggJFgrpFCfj
MvQBJMBQhjQFNFnjnj
dtlZmRtLmjSTSLLtTtNVwWzDRzDVwwWFwnNn
dmmLCqTdcLqtLGqjBhpfHqBGpv
PBPRhjTPPlLRBvlvfwffqJGfpG
rHtMtrszFtSgbFrrggrFgMnwWGzmQqWvGWzGQpJGfNqqNz
FggcbSMntVgMdRCwZcjChLCT
lCqqBlCwlnDqPZTZZBLNdjJLwttNWjjdzJzc
fVfMbvbvmbVsmSsmMVWNtzzcjgLWgjztMMtg
VVmFhFRSfbQsvVQmvSfhSsmzHlCZqrrBrDBrHZPRTZnnzB
CRrDWmzRRQMmDqrrBgBQmtHljhHwtwlwplcBjHGwwB
PWfPSWnvsNZSZdfjHjZtGHjchllltl
WVsnbSPTbNdbmqTQmmrmLzTq
cGtMBGSJDgtgMBsBMgMvWWSHWjpjzHTWTPpqWzqW
mNVQNsdVsdhLmCpTWWjmCjTT
NQQwrfbQrNQNbrrdLwfQsZdgFbBBFBgggRGRDMRFFMRDgM
lFnqgqWQvHWqgvlVglvqjPjcLdfLfBPLnrbLNLcN
hmTmthppsRtpTRRTZMpSbLdNjNcJLcrcBNbJBZZc
smmpRsTtpSSsRGhppmmhdCMGWwqFQgWGWWDgWwVFHQqHgg
mWFjmcdcFWcSSQjzrpvrwRGvTwQGGG
HRJfgMZVhtRlHJHBVJTGvGppbpbvvGTvTtrv
glsgVMVqffdnPRDcqLnL
MtvLJdmLLTvSSCtSzLSTcDhRjRftQjjssshfQNjPtf
nlggrFWzRsfFjVQN
WgwwBgbgZBHGBnccTzMCLTZJmLLL
sRtHTBBHZtDTtZhdPzWdGcdVFdJmGcnm
wpwMLWCgvfNvwvwbbCrwgfzPncrJPSFVGPnrcJSVznmV
bLpvwQwMwpjWMgfvgZTsDsBttqHRjTqHlH
mpmGpCpmlpmwfmCQVppCVfQSSjvSqgWvvvDgNwWDgnnDnW
RBLsHRJBRrHJWFDWSNqFWj
zZBLdsdcZrsBjGfpGVpTTPGlVc
NBbTzgwSNmrFWpVrzrFM
LnZQtQlZVnMrFBBG
CCdtddBtPdNqcvHSCCcg
ZFbZPHbZPTQVVlsGNF
qtvDWvgRftqGNccCNVThDs
fRwGBBjBppdMdBMZ
GffflsZsPZVfjsssNfZsJNNZVcMDSqMWFcwFMMpcTMTTFSTS
LhrCmvzcRbbhtmRdTCMDwWMpDWqqqMpW
dvRQmBBvLzBRRvRhhcdbhdRgjHQNllJsfsNlZZljZGGNQN
wjbMPsbfLzVCTMVbjLplmpshhSpHShhJhtsm
ZrcqZTDTGDqFdJtGmdGSpl
QNNrWvQRqRNWnTQRvqjPbjfWbCBCMbMLBwMV
wRPRsppFfWJRlPRPFlpJfwSMzzZTBwBtZTTCMCMtdz
vGLGrjcfrLVGjfnGTMCMtNNnCTnMtCBd
VrjqhjhLVcrGVRqJmqQspmfFWm
LRfdnmwMwdSBmfvJNrrgLhCNgqqJWs
llctPPVTcPStgJgshCsrCs
DpTlFpFVRFZRFFSv
sPgRgsmdcqmgSvvFRRRRdqdFfTWZhhdZrZbbWfTpwDfbWTbw
jLCCHtLljJzjlplfZSlwTfprZZ
tBHVjQHzHQJBtSVmvRsvvFRqnGgv
spppVDbVcbgVSFgFZZbGZgbJMRBTvHTvJJHGtHRwtMGvHT
LldflzQLLQmQWQQfnwMWwHJtTtwRBcBt
CPjfhCmNmNfFVchpchFVhp
bZQJgQmQmTgnLBRtNPNnml
ccszcqldGzhszrVsqdlHVNwLpppwHPHRtBBppDNRLt
VSzVhVdcfrrhcqGrVhrssQQlMbJvFjMgbFSQggCvCv
hHWVWhhlZDZVWNTgczWLjbtcTFFj
JJnPnCdBCBnnRCjSsjStBgsbFttb
MRpgCpGqdPRppJwpnRqRfZZhmvhHDrhllDHhhZGZ
SPcgLDcLLnWFWCNVCRPT
fhZQtsbtmbmfZTVTVRWfNvTCTT
jhbbmzRsQzpLDcgLHLjg
GSFRHrCCGRJDJtrgWdrL
stcVQshQZBsBmjMsZhmMQQWDDvNWdncNWvzLgdDnzdDN
sVwMBQBhVVjtQZVPlSfPCfwRpSCpRl
bBHHJMJvBvWMJWqqccNNPhMCrclChQCC
RPppPgfpwgmcQgrhmm
tfwTwpFPGGwZSRtpVjJHbHLvSvLSqVLL
jlJfZGjljJPBqJGnfGVMqGfrFWWddvDmFRDcmdFDdDvbDM
hTCTsgsgwhTbvRdcFmsddpFd
wbQNHTQLgCwSThhCgwnZnJfqnqJBlNlBnnVl
CLlfbjjbLlbbDGbLzfCGhdtdWBthdBWsHvWHBnntWs
rmJRJFqrDwVFTwFmSJvtvMtdJMMHBdBBndWt
ZVrVVZpgTpZFSqmZqRNlNNfQQbpGjDQbbpPl
mVCrhGHGmZhrNlDwbWnLWWvGLWWwnd
PNsqgzspsgNFJNFfzqpWSWdwSvSPnvdWbSbvjd
NzgJzqMcgscQqJcpJRzBmlrBRBDDlHZBBBHtHZ
NJmNJDwcMmJNMbJJDNDqcGcsWRWHQzRPQjZLRGZWLQsjZQ
dgSnTBgdpddtgShSTZjLRhRLHqWPPhPRPQ
VgdTpBntlvBVrlfcbqJcMrfmcqmb
wvqwvPwNJgFmLdvDJFDmDLvJlQZpMzSpBVflpdSSMlQnfldS
WjCcRZCWRjjRtsZhRRhpSVBVnzplBfWnfBfSQz
CbRbcsjHZrhbTRtsGbCrgNgDDPFFqvvJvJFDFw
GlsCrbCChShqgqlbSCcVbqgVhBwjBDFBhBhdDWvwBFFvWvDv
THmHMmtMnLfHRnzRZnfLBDWWsWzWFNsvWjjvjvFF
mpHRtmZffHTTMpmLMLLnJtJCgScScsPlblcpCrPbblCPlq
vscDLrcvrsLNStdTfBCvgJTqGBdd
bwLbzRhbbdTfbgCB
pplQzLwmPZVMStcDjFtQrS
RMjCrhFJhRVRVCCFFsvmnvqrmbvqmqSmbrvm
tzfpBgTHzttGzZpBfHGDBZHbccnGqbmvdNlGnSnlcvSwbn
pDWTHDTzgTfWZpVVsWSPjRFSMsFs
fmrfmrwVfjmrzjqCsqqvjsvvpG
hFDVtFStVtJnPPtJNHbtQWGbQsCvCsQgpWGggdQC
NBSDSNHStHNHnhStHNNrcflrmTzBlwmzrlMVVw
SjtZZSdNcDldPQqndl
BbgzgWgTmTBfwrbnDjQDwVPwDlnsVq
zBBrCTTMBWLMWmfMfbbmrMtjNZLFJRRZSSvFFtStvGGJ
CTCGLGCFRRSMGnZnLCTfdffhpbNbDfpdZBvhdv
rJlqclVPHJWVrgPPQqjqgJlhBhDBBQdvbhwvNfhswfNpvb
tltrcrHjlVWVCDzSGCCzLCGt
sbHHsbCCHbLSVfJbbfSLNJBzvzMMPrhPPNztZlZNZhdt
GTWjplTgDnGmQGpQnQhZrvvBMPztPzvrzvjZ
mQgGWllcFcTFmgwcDppDQGTCqfsSLqsfSbqJqLSSFsbRfF
jslsFjLLLLvFwWtQFTFDJQWp
dGzdrNmRWqVBGcTbwpRDRnbJDRhT
qzqzrrPNNrmfLPsjglHjgW
QjCHcPfcgQSgPPcffQSmmmLmrJJpNpBMrJMtFrBBBMFrrpNS
VGVZfDbbVVZWGvDbFrlBZNJBNlNMwwtM
sbvfhqTGTRnhTVGvzgHmgQLQmPqzmPLm
sLwnMHnbnLMjGpZsjGGtpc
ggvJrNNTQgQrNvgqBqZCCjClWjGtWjCpGJFW
TVdrqvVrTNTzBqQQzTRMfHbMwMbZMdMbHwRD
bcfJQQJHsQPCpdpWdPbb
RHjHDwZtrZmRDDtwtjRBVFdWVrrrBClldVphCF
zDgwgNzjmDnMnzMMHncG
vMHRvMhvHWRBRDHhRBwWvRBqLqbGwqnqnnNTbNqdNbbVVr
pslgcZszJltrsZcZgNnnqbSSTSSndbNbzS
cZcgsZgZZgPgmcpfJtfttWBQvmFWjDQDhBmFjDHvFr
bVbBvdTTVLbCgCznLJsJcwHPczfz
NFcDphSDrFjGtZNZjplZGZFnzPHPrzHHzJMnnwfPsPsRJs
cGtGljFmWdvqmVCV
qSNbTvcvTGTvGcgtBNvcbdrdjrnjRnjRVHdDqHrRHj
ZZZZPLWPzPDCCsCRnRdwVFnjdwPVFP
ChlCLLZftfcBvfDv
cRtfctVgmRclmBFGbbMBDDFPtD
svQZhHSHssjTvjpQjSSBBMJMJGDBpPbMzzpGzP
ZsvsCTWhCHhSwwjrwbndldlRnfRNmb
PQdTgdGpRcTccCfj
hHFLHlHBhBlmlDFzHrhhfZNZbfNZcVWNVVZRDjCC
LFLLMHJHSBhBFGGnMMvsGtGGtj
fwmVnVCDVqpNQqqb
ddBcZZWdvGWzBzsWvLvddlNHcHQPbQqqJQNNQHPHQT
WgGvsMMzvgbntDhCmt
JjwhFMmwjJwmCgTgSCSFlPLg
WWbsbVtftBZWtnWtncbQvctTGLpLgCpzPPPlllpzlgPPTQ
TBvnfBffWsfVtTvbZBTNjwjqddhMNqwRMMhdRMrq
SllrbtTSQrSQrbrvvMvzFDsBsssWpWdWbGpGBWNWNW
hhCfmmmjmPLCfmnPLfqPgqqNNBpjZBZQDNQdpWNpdBBsBp
RhLfPhQLQfCRnHfqTHHrFJMrttTwTtzt
BFrFBJMMJnnsNJBFCdLCnmvzbPdCmPnc
LDLVHQRfDvdHdcCmcv
llQDwqSVLwZLZSgsGZMNMgTjTMTr
mrwdbqRhdCNGgZBHbH
jVTPMjvjpvMfTfQfPlpHHZNnNBHgZDGsGMnCsZ
TLlfQpffQvvzhtNqztRFtzcm
DDfvJZZPDHVPSPcSvcgcWCsWQcTTdhQTTh
dMwpbdjRtrFhhTsTFQWqhC
bGRdNpbzlvLfDfZlLZ
bdPQdcpdbpjFqpQcQwqqhhNRhJvWRfrrWBsJrfwN
mMtlZfmtnLZtSnGDlmGWRRhrWLhJsBRvgRWghh
DnMGCtmCzfGMbjdQbVzpqcFH
jwnGggRBvvpBZCljCsCWrhhrsh
FVMcFLqLMqcJfVtDqMJcHMHWCSblzzrWsdhSLlSzbrGCLz
HQVFPDtDQDFFNTZpPgNnGgNn
HNBHNqlqHJQBRNvdmZvmPdZZlpnT
bDbbhDgSfzVVfnvPmfHmTZZd
jgzbwrhVsDgsDWLwJqqBMqcqHL
tzNtJzsJVBHzbjbglCHc
nfmnGnmPhntCgHvtvmCj
MStTwrMTWrTdBZSNLZJNVQ
NVjmwmVGGwGFHstwFHMhTh
psRSzzscZscZpgQQzqQtBBHTTlThHHtTTh
rCprbpZccggcrRzbbRRbscvVVWWvNfvVWnGDCWVNddmd
rphfGDgtPtllrPlFlGrhGjnmnTnjcBsncBBVpTTBmc
SqqZMJCLwgCwJgQRqqgZQNwdBBsBBHVBdTHNsnVNBTccnc
MJqZZMbqgzRCSJZwPtFfGzWhrrfGttWl
cSZqqcwbqVzqCbqVqVZPsvvDCDrffngvphggndhdGh
tTNTMWJNQJHMNGSSprfdGnfdth
WNRHWWMJSRWzswbczsVPRs
HCgcSMhSMBGMdvGf
RNQqbDQqFdRFdmTZfGtPZvtGlQffll
mNpdNrRDbTNrmbpzmpWmbpWcswhcHcjhscSHjSgVHwHn
MwgcFgwMMcscCbMFsMFCgMgPPLWPvptvBvPvtvvWmBBzwG
nhQQjTJRVDdQJrPpmnGGBmvtGvLz
HdJQdJHjrJQDBQjhQVQJhdJcqlFHcSqsNbCbCqCHFqCFgC
JvTnvWtdJLbhJHbMwwHjcGHCwHwQGQ
mqtmsllmfqVFwMwMrrPjmQrC
lfztRZSlRDRVzfdpWnSvWhNdbnpp
rSvrgggzHTNzrHtnptpmlDngZjWj
MdMhqMhsfMSRcGqRsQQRctjjdDnjtjClCjjpZnDlnt
BBMRsQRfRcscGqBfRRsBssPBLLzNLFPwvVFFPTLbbLwHHTvS
pCmCfdPFzmsFsDhFFDsttptpRtJjLnlJRtttHt
ZQwgWZgqJhTTRtgV
GNqWNvcqqQQrMMWcQzDDsSzBDBSssSmhhr`